#ifndef __GLOW_EVENTS_H__
#define __GLOW_EVENTS_H__

#define GLOW_MOUSE_BUTTON_UNKNOWN 0
#define GLOW_MOUSE_BUTTON_LEFT 1
#define GLOW_MOUSE_BUTTON_RIGHT 2
#define GLOW_MOUSE_SCROLL 3

#define GLOW_MOD_SHIFT 0x01
#define GLOW_MOD_CONTROL 0x02
#define GLOW_MOD_ALT 0x04
#define GLOW_MOD_COMMAND 0x08
#define GLOW_MOD_CAPSLOCK 0x10
#define GLOW_MOD_FUNCTION 0x20

#define GLOW_KEY_NONE 0
#define GLOW_KEY_BACKSPACE 8
#define GLOW_KEY_TAB 9
#define GLOW_KEY_RETURN 13
#define GLOW_KEY_ESCAPE 27
#define GLOW_KEY_DELETE 127
#define GLOW_KEY_LEFT_ARROW 128
#define GLOW_KEY_RIGHT_ARROW 129
#define GLOW_KEY_DOWN_ARROW 130
#define GLOW_KEY_UP_ARROW 131
#define GLOW_KEY_LEFT_SHIFT 132
#define GLOW_KEY_RIGHT_SHIFT 133
#define GLOW_KEY_LEFT_ALT 134
#define GLOW_KEY_RIGHT_ALT 135
#define GLOW_KEY_LEFT_CONTROL 136
#define GLOW_KEY_RIGHT_CONTROL 137
#define GLOW_KEY_LEFT_COMMAND 138
#define GLOW_KEY_RIGHT_COMMAND 139
#define GLOW_KEY_CAPS_LOCK 140
#define GLOW_KEY_FUNCTION 141
#define GLOW_KEY_F1 142
#define GLOW_KEY_F2 143
#define GLOW_KEY_F3 144
#define GLOW_KEY_F4 145
#define GLOW_KEY_F5 146
#define GLOW_KEY_F6 147
#define GLOW_KEY_F7 148
#define GLOW_KEY_F8 149
#define GLOW_KEY_F9 150
#define GLOW_KEY_F10 151
#define GLOW_KEY_F11 152
#define GLOW_KEY_F12 153

#endif // __GLOW_EVENTS_H__
